/**
 * Generated client SDK for a `token-to-css serve` mesh.
 *
 * The client subscribes to the server's SSE push channel and keeps a live,
 * resolved token tree in memory. It hot-swaps the active mode/brand on the
 * document without a rebuild and exposes the same typed tree `kit` emits.
 *
 * Framework-agnostic (no React/DOM-only APIs beyond a guarded `document`/
 * `window` touch) and intentionally tiny.
 */
export function buildClientJS(options = {}) {
  const streamUrl = options.streamUrl || "/events";
  const name = options.name || "TokenClient";
  return `/* Generated by token-to-css serve — do not edit. */
(function (root, factory) {
  if (typeof module === "object" && module.exports) module.exports = factory();
  else root.${name} = factory();
})(typeof self !== "undefined" ? self : this, function () {
  function ${name}(opts) {
    opts = opts || {};
    var streamUrl = opts.streamUrl || ${JSON.stringify(streamUrl)};
    var snap = null;
    var mode = null;
    var brand = null;
    var listeners = [];
    function emit(tree) {
      snap = tree;
      for (var i = 0; i < listeners.length; i++) listeners[i](tree);
    }
    function applyAttrs() {
      if (typeof document === "undefined") return;
      var d = document.documentElement;
      if (mode != null) d.setAttribute("data-mode", mode);
      else d.removeAttribute("data-mode");
      if (brand != null) d.setAttribute("data-brand", brand);
      else d.removeAttribute("data-brand");
      var theme = [brand, mode].filter(Boolean).join("-") || "default";
      d.setAttribute("data-theme", theme);
    }
    function set(o) {
      o = o || {};
      if (o.mode !== undefined) mode = o.mode || null;
      if (o.brand !== undefined) brand = o.brand || null;
      applyAttrs();
      if (opts.onChange) opts.onChange(snapshot());
    }
    function snapshot() { return snap; }
    function on(cb) { listeners.push(cb); return function () { listeners = listeners.filter(function (f) { return f !== cb; }); }; }
    function connect() {
      if (typeof EventSource === "undefined") return;
      var es = new EventSource(streamUrl);
      es.onmessage = function (ev) {
        try {
          var msg = JSON.parse(ev.data);
          if (msg && msg.tree) emit(msg.tree);
        } catch (e) {}
      };
      es.onerror = function () {};
      return es;
    }
    var es = connect();
    return {
      set: set,
      setMode: function (m) { set({ mode: m }); },
      setBrand: function (b) { set({ brand: b }); },
      snapshot: snapshot,
      on: on,
      close: function () { if (es) es.close(); }
    };
  }
  return ${name};
});
`;
}
