import { resolveReferences } from "./references.js";
import { validateTokens } from "./schema.js";

/**
 * v14 component layer — themeable primitive CSS.
 *
 * `buildComponentsCSS(tokens, options)` emits buttons, inputs, cards, and
 * focus rings as plain, zero-dep CSS that references the kit's custom
 * properties via `var()` — so a token edit restyles every component
 * end-to-end with no rebuild of the component layer itself. The output is
 * ordinary CSS, so the v9 consumer lint (`lintConsumer`) scans it like any
 * other consumer source.
 *
 * Opt-in: `buildKit(tokens, { components: true })` includes it, and
 * `token-to-css kit --components` writes `components.css`. Core never changes
 * for new components — this module is the seam.
 */

export const COMPONENT_PREFIX = "ttc";

/** Token paths the component layer reads (contract tie-in — all optional). */
export const COMPONENT_TOKENS = [
  "color.primary",
  "color.primaryHover",
  "color.primaryFg",
  "color.background",
  "color.surface",
  "color.text",
  "color.muted",
  "color.border",
  "color.danger",
  "color.focus",
  "radius.sm",
  "radius.md",
  "radius.lg",
  "font.family",
  "font.sizeBase",
  "control.height",
];

/**
 * The component contract: required vs optional token paths. Everything is
 * optional — every rule falls back through a `var()` chain to another
 * well-known token — so any token file produces usable CSS.
 */
export function getComponentContract() {
  return { required: [], optional: [...COMPONENT_TOKENS] };
}

function countLeaves(node) {
  if (node && typeof node === "object" && !Array.isArray(node)) {
    if ("$value" in node) return 1;
    return Object.values(node).reduce((n, v) => n + countLeaves(v), 0);
  }
  return 1;
}

/**
 * Build the primitive component stylesheet.
 *
 * Options: `{ prefix = "ttc", include = ["button","input","card","focus"] }`.
 * All themeable values are `var(--token)` references (never inlined literals),
 * so editing a token and re-running `kit` (or pushing through `serve`) visibly
 * restyles the primitives.
 */
export function buildComponentsCSS(tokens, options = {}) {
  if (options.validate !== false) validateTokens(tokens);
  // Resolve once so unknown `{refs}` fail fast — values themselves are never
  // inlined; components always read the live custom properties.
  resolveReferences(tokens, { reduce: true });
  const prefix = options.prefix || COMPONENT_PREFIX;
  const include = new Set(options.include || ["button", "input", "card", "focus"]);
  const n = countLeaves(tokens);
  const out = [
    `/* Generated by token-to-css kit --components — ${n} token(s).`,
    `   Themeable primitives (button, input, card, focus ring).`,
    `   All theme values are var() references: edit a token and every`,
    `   component restyles end-to-end. */`,
  ];
  const P = (n) => `${prefix}-${n}`;

  if (include.has("button")) {
    out.push(
      `.${P("button")} {`,
      `  display: inline-flex;`,
      `  align-items: center;`,
      `  justify-content: center;`,
      `  gap: 0.5rem;`,
      `  min-height: var(--control-height, 2.5rem);`,
      `  padding: 0.5rem 1rem;`,
      `  font-family: var(--font-sans, var(--font-family));`,
      `  font-size: var(--text-base, var(--font-size-base));`,
      `  color: var(--color-primary-foreground, var(--color-text));`,
      `  background: var(--color-primary);`,
      `  border: 1px solid var(--color-primary);`,
      `  border-radius: var(--radius-md, var(--radius));`,
      `  cursor: pointer;`,
      `}`,
      `.${P("button")}:hover {`,
      `  background: var(--color-primary-hover, var(--color-primary));`,
      `  border-color: var(--color-primary-hover, var(--color-primary));`,
      `}`,
      `.${P("button")}:active {`,
      `  background: var(--color-primary-hover, var(--color-primary));`,
      `  filter: brightness(0.95);`,
      `}`,
      `.${P("button")}:disabled {`,
      `  opacity: 0.5;`,
      `  cursor: not-allowed;`,
      `}`,
      `.${P("button")}--secondary {`,
      `  color: var(--color-text);`,
      `  background: var(--color-surface);`,
      `  border-color: var(--color-border);`,
      `}`,
      `.${P("button")}--secondary:hover {`,
      `  background: var(--color-surface-alt, var(--color-surface));`,
      `  border-color: var(--color-border);`,
      `}`,
    );
  }

  if (include.has("input")) {
    out.push(
      `.${P("input")} {`,
      `  display: block;`,
      `  width: 100%;`,
      `  min-height: var(--control-height, 2.5rem);`,
      `  padding: 0.5rem 0.75rem;`,
      `  font-family: var(--font-sans, var(--font-family));`,
      `  font-size: var(--text-base, var(--font-size-base));`,
      `  color: var(--color-text);`,
      `  background: var(--color-background);`,
      `  border: 1px solid var(--color-border);`,
      `  border-radius: var(--radius-md, var(--radius));`,
      `}`,
      `.${P("input")}::placeholder {`,
      `  color: var(--color-muted);`,
      `}`,
      `.${P("input")}:focus {`,
      `  outline: none;`,
      `  border-color: var(--color-primary);`,
      `  box-shadow: 0 0 0 3px var(--color-focus, var(--color-primary));`,
      `}`,
      `.${P("input")}:disabled {`,
      `  opacity: 0.5;`,
      `}`,
    );
  }

  if (include.has("card")) {
    out.push(
      `.${P("card")} {`,
      `  padding: 1rem;`,
      `  color: var(--color-text);`,
      `  background: var(--color-surface);`,
      `  border: 1px solid var(--color-border);`,
      `  border-radius: var(--radius-lg, var(--radius-md, var(--radius)));`,
      `  box-shadow: var(--shadow, none);`,
      `}`,
      `.${P("card")}--elevated {`,
      `  box-shadow: var(--shadow-lifted, var(--shadow));`,
      `}`,
      `.${P("card")}__title {`,
      `  margin: 0 0 0.5rem;`,
      `  font-family: var(--font-sans, var(--font-family));`,
      `  font-size: var(--text-lg, var(--text-base, var(--font-size-base)));`,
      `}`,
    );
  }

  if (include.has("focus")) {
    out.push(
      `.${P("button")}:focus-visible,`,
      `.${P("input")}:focus-visible,`,
      `.${P("card")}:focus-visible {`,
      `  outline: 2px solid var(--color-focus, var(--color-primary));`,
      `  outline-offset: 2px;`,
      `}`,
    );
  }

  return `${out.join("\n")}\n`;
}
