export type Tokens = any;

export function convert(tokens: Tokens, options?: any): string;
export function convertToMap(tree: Tokens, locations: any, options?: any): { css: string; map: any };
export function flattenTokens(input: any, prefix?: any[], opts?: any): Record<string, string>;
export function normalizeW3C(input: any): any;
export function applyMap(flat: any, mapObj?: any): any;
export function toCSS(flat: any, options?: any): string;
export function toSCSS(flat: any, options?: any): string;
export function toCSSModules(flat: any, options?: any): string;
export function toBarefoot(flat: any, options?: any): string;
export function resolveReferences(tokens: any, options?: any): any;
export function registerFunction(name: string, fn: (...args: any[]) => any): void;
export function registerFormat(name: string, fn: (...args: any[]) => any): void;
export function registerPlugin(plugin: any): any;
export function validateTokens(tokens: any): boolean;
export class TokenValidationError extends Error {}
export function lintTokens(tokens: any, options?: any): any;
export function checkContract(tokens: any, contract: any): any;
export function buildKit(tokens: any, options?: any): any;
export function buildKitCSS(tokens: any, options?: any): string;
export function buildThemeJS(options?: any): string;
export function buildBindings(tokens: any, options?: any): { ts: string; js: string };
export function buildPreviewHTML(tokens: any, options?: any): string;
export function splitThemes(tree: any): any;
export const THEME_JS: string;
export function buildDocsSite(tokens: any, options?: any): string;
export function buildExplorerHTML(tokens: any, options?: any): string;
export function buildProvenance(tokens: any, options?: any): string;
export function reverse(css: string, options?: any): any;
export function reverseStyleDictionary(sd: any, options?: any): any;
export function applyReversedIntoSource(...args: any[]): any;
export function computeDrift(...args: any[]): any;
export function canSetPath(...args: any[]): any;
export function buildNameRegistry(tokens: any, options?: any): any;
export function registryFromJSON(json: any): any;
export function setByPath(obj: any, path: any[], value: any): void;
export function getByPath(obj: any, path: any[]): any;
export function mergeRegistries(...args: any[]): any;
export function parseLocated(input: any, source?: string): any;
export function buildClientJS(options?: any): string;
export function addVersionMarkers(tokens: any, semver: string): any;
export function getDeprecations(tokens: any): any;
export function createChangeRequest(...args: any[]): any;
export function approveChangeRequest(...args: any[]): any;
export function rejectChangeRequest(...args: any[]): any;
export function applyChangeRequest(...args: any[]): any;
export function getImpactGraph(tokens: any): any;
export function getTransitiveDependents(tokens: any, path: string): string[];
export function generateCodemod(tokens: any, opts: any): any;
export function applyCodemod(tree: any, codemod: any): any;
export function generateCSSCodemod(tokens: any, opts: any): any;
export function buildOrgManifest(...args: any[]): any;
export function validateManifest(...args: any[]): any;
export function resolveOrgTree(...args: any[]): any;
export function lintOrg(...args: any[]): any;
export function listPackageVersions(...args: any[]): any;
export function resolvePackage(...args: any[]): any;
export function mergeOrgRegistries(...args: any[]): any;
export function buildFederatedManifest(...args: any[]): any;
export function validateFederatedManifest(...args: any[]): any;
export function resolveFederatedTree(...args: any[]): any;
export function analyzeCrossOrgLock(...args: any[]): any;
export function createNamespacedAuth(...args: any[]): any;
export function createFlatNamespacedAuth(...args: any[]): any;
export function createNamespacedMiddleware(...args: any[]): any;
export function createOrgAuth(...args: any[]): any;
export function orgRoomKey(...args: any[]): any;
export function bumpVersion(...args: any[]): any;
export function classifyRelease(...args: any[]): any;
export function generateChangelog(...args: any[]): any;
export function release(...args: any[]): any;
export function semverSatisfies(...args: any[]): any;
export function analyzeLockfile(...args: any[]): any;
export function bisectToken(...args: any[]): any;
export function renderSideBySide(...args: any[]): any;
export function diffTokens(a: any, b: any): any;
export function buildSourceMap(css: string, locations: any, options?: any): any;

export function parseColor(str: string): any;
export function formatColor(c: any): string;
export function mix(c1: any, c2: any, weight?: number): any;
export function withAlpha(c: any, a: number): any;
export function lighten(c: any, amount: number): any;
export function darken(c: any, amount: number): any;
export function oklabToRgb(...args: any[]): any;
export function oklchToRgb(...args: any[]): any;
export function labToRgb(...args: any[]): any;
export function rgbToOklch(c: any): any;
export function oklchDistance(a: any, b: any): number;

export const BAREFOOT_MAP: Record<string, string>;
export const TAILWIND_MAP: Record<string, string>;
export const OPENPROPS_MAP: Record<string, string>;
export function mapToBarefoot(flat: any, map?: any): any;
