/**
 * Compose (Jetpack Compose) connector (v14 Universal Connector Hub).
 *
 * Translates a token tree into a Compose `MaterialTheme`-shaped theme plus the
 * full resolved token tree (the canonical, lossless representation — mirroring
 * the Storybook connector's `{ tokens, theme }` shape). The `theme` object is
 * a convenience projection of well-known Material keys; `tokens` round-trips
 * byte-for-byte.
 *
 * Pure transforms (`tokensToComposeTheme` / `composeThemeToTokens`) are
 * transport-agnostic and unit-testable without a network. `push`/`pull` talk
 * to a configurable `url` (any adapter endpoint that stores the theme JSON)
 * when a `fetchImpl` is supplied.
 *
 * Zero core changes: registers through `registerConnector` only, plus an
 * opt-in `compose` output format (Kotlin source).
 */
import { toTransportTree, registerConnector } from "./connect.js";

// Well-known Material theme keys sourced from token paths.
const THEME_MAP = {
  primary: "color.primary",
  onPrimary: "color.primaryFg",
  secondary: "color.secondary",
  background: "color.background",
  surface: "color.surface",
  error: "color.danger",
  onBackground: "color.text",
  onSurface: "color.text",
  outline: "color.border",
  fontFamily: "font.family",
  cornerSmall: "radius.sm",
  cornerMedium: "radius.md",
  cornerLarge: "radius.lg",
};

function getByPath(node, path) {
  let cur = node;
  for (const p of path.split(".")) {
    if (cur == null) return undefined;
    cur = cur[p];
  }
  return cur;
}

function setByDottedPath(node, dotted, value) {
  const parts = dotted.split(".");
  let cur = node;
  for (let i = 0; i < parts.length - 1; i++) {
    cur[parts[i]] = cur[parts[i]] || {};
    cur = cur[parts[i]];
  }
  cur[parts[parts.length - 1]] = value;
}

export function tokensToComposeTheme(tokens) {
  const tree = toTransportTree(tokens);
  const theme = {};
  for (const [key, path] of Object.entries(THEME_MAP)) {
    const v = getByPath(tree, path);
    if (v !== undefined) theme[key] = v;
  }
  return { tokens: tree, theme };
}

export function composeThemeToTokens(doc) {
  if (doc && doc.tokens) return doc.tokens;
  // Best-effort reconstruction from a projected theme object.
  const out = {};
  for (const [key, path] of Object.entries(THEME_MAP)) {
    if (doc && (doc[key] !== undefined || (doc.theme && doc.theme[key] !== undefined))) {
      const v = doc[key] !== undefined ? doc[key] : doc.theme[key];
      setByDottedPath(out, path, v);
    }
  }
  return out;
}

/** `#rrggbb` / `#rgb` -> `0xFFRRGGBB`, else null (emitted as a comment). */
function composeColor(value) {
  const m = /^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/.exec(String(value).trim());
  if (!m) return null;
  let hex = m[1];
  if (hex.length === 3) hex = hex.split("").map((c) => c + c).join("");
  return `0xFF${hex.toUpperCase()}`;
}

function pascal(s) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

/** Emit an idiomatic Kotlin `TokenTheme` object from a resolved token tree. */
export function buildComposeKotlin(tree) {
  const { theme } = tokensToComposeTheme(tree);
  const colors = [];
  const values = [];
  for (const [key, value] of Object.entries(theme)) {
    const field = pascal(key);
    const c = composeColor(value);
    if (c) colors.push(`    val ${field} = Color(${c}) // ${value}`);
    else if (value !== null && typeof value === "object")
      colors.push(`    // ${field}: non-scalar token (see tokens) ${JSON.stringify(value)}`);
    else values.push(`    const val ${field} = ${JSON.stringify(String(value))}`);
  }
  if (!colors.length) colors.push("    // (no mappable color tokens)");
  return [
    "// Generated by token-to-css (compose connector) — do not edit.",
    "import androidx.compose.ui.graphics.Color",
    "",
    "object TokenColors {",
    ...colors,
    "}",
    "",
    "object TokenValues {",
    ...(values.length ? values : ["    // (no mappable non-color tokens)"]),
    "}",
    "",
  ].join("\n");
}

/**
 * Opt-in Compose connector. Registers a `compose` output format and returns
 * a `push`/`pull` object that talks to a theme adapter endpoint.
 */
export function registerComposeConnector({ fetchImpl, url, token } = {}) {
  const fetchFn = fetchImpl || (typeof fetch !== "undefined" ? fetch : null);

  function headers(extra = {}) {
    return {
      "content-type": "application/json",
      ...(token ? { authorization: `Bearer ${token}` } : {}),
      ...extra,
    };
  }

  async function pull() {
    if (!fetchFn) throw new Error("compose connector: no fetch implementation available");
    if (!url) throw new Error("compose connector: no url configured");
    const res = await fetchFn(url, { headers: headers() });
    if (!res.ok) throw new Error(`compose pull failed: ${res.status}`);
    return composeThemeToTokens(await res.json());
  }

  async function push(tree) {
    if (!fetchFn) throw new Error("compose connector: no fetch implementation available");
    if (!url) throw new Error("compose connector: no url configured");
    const res = await fetchFn(url, {
      method: "PUT",
      headers: headers(),
      body: JSON.stringify(tokensToComposeTheme(tree)),
    });
    if (!res.ok) throw new Error(`compose push failed: ${res.status}`);
    return res.json();
  }

  registerConnector({
    name: "compose",
    pull,
    push,
    formats: {
      compose: (_flat, opts) => {
        const tree = opts && opts.resolvedBase ? opts.resolvedBase : {};
        return buildComposeKotlin(tree);
      },
    },
  });
  return { pull, push, tokensToComposeTheme, composeThemeToTokens, buildComposeKotlin };
}
